//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E9101Main.rc
//
#define IDD_E9101MAIN_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_SYSSET_DIALOG               129
#define IDD_LANGUAGESET_DIALOG          130
#define IDD_SKIN_DIALOG                 131
#define IDD_INFO_DIALOG                 132
#define IDD_ABOUT_DIALOG                133
#define IDD_BRIGHTNESS_SET_DIALOG       134
#define IDD_TIMESET_DIALOG              135
#define IDD_DLG_DRIVESETTING            136
#define IDD_SYSINFO_DIALOG              137
#define IDD_VOLUME_DIALOG               138
#define IDD_DIALOG_GAME                 140
#define IDD_DLG_FILE_DOWNLOAD           141
#define IDD_DLG______                   142
#define IDD_DLG_DIAODU                  142
#define IDD_DIALOG_PHONEBOOK            143
#define IDD_DIALOG_DIA                  144
#define IDD_PANEL_320X240               145
#define IDD_DLG_DRIVE_ECONOMY           146
#define IDD_DLG_FAILURE_DIAGNOSTIC      147
#define IDD_DIALOG_PHONELOG             148
#define IDD_DIALOG_NAVISTART            149
#define IDD_DLG_DRIVE_RECORD            150
#define IDD_DLG_SECURITY_MONITOR        151
#define IDD_DLG_J1939_DIAGNOSTIC        152
#define IDD_DIALOG_EBOOK                153
#define IDD_DIALOG_GPS_STAR             154
#define IDI_ICON_GPS_WEAK               156
#define IDI_ICON_GPS_STRONG             157
#define IDD_DLG_VIDEO                   158
#define IDD_DLG_VEHICLE_INFO            159
#define IDD_DLG_DIAL_IN                 160
#define IDD_DIALOG_POWERSTATUS          161
#define IDD_DIALOG_LIGHTSET             163
#define IDD_DIALOG_INFO                 165
#define IDD_DIALOG_SYSSET_KEYVOL        166
#define IDD_DIALOG_NAVISET              167
#define IDD_DIALOG_BROWER               168
#define IDD_DLG_DRIVE_INFO              169
#define IDD_DLG_PUSH_TO_TALK            170
#define IDD_DLG_NAVI_BRO                171
#define IDD_DIALOG_SET_PIN              172
#define IDD_DLG_OILCONSUM               173
#define IDD_DIALOG_PAIR                 175
#define IDD_DIALOG_PHONEBOOK_EDIT       176
#define IDD_DIALOG_CONFIRM              177
#define IDD_DIALOG_PHONEBOOK_CHECKIN    178
#define IDD_DIALOG_NUMBER               179
#define IDC_CURSOR1                     179
#define IDD_DIALOG_DIAL_NUMBER          180
#define IDD_MEDIA_MAIN                  181
#define IDD_SMS_MAIN                    182
#define IDD_SMS_INBOX                   183
#define IDD_SMS_OUTBOX                  184
#define IDD_SMS_DRAFT                   185
#define IDD_DLG_DRIVE_SECURITY          186
#define IDD_SMS_SENDING                 187
#define IDD_GSM_DIAL                    188
#define IDD_GSM_DIALING                 189
#define IDD_GSM_DIAL_MAIN               190
#define IDD_GSM_CALLING                 191
#define IDD_SMS_INFO                    192
#define IDD_PBOOK_MAIN                  193
#define IDD_GSM_NET                     194
#define IDD_DIALOG_NUMB_SET             195
#define IDD_GAME_MANUAL                 196
#define IDD_DLG_PINSET                  197
#define IDD_DIALOG_IPSET                198
#define IDD_DLG_PWDINPUT                199
#define IDD_DIALOG_DISPATCH             200
#define IDD_DLG_FM                      201
#define IDD_DIALOG_MSGBOX               202
#define IDD_DIALOG_EVENT                204
#define IDD_DIALOG1                     205
#define IDD_DIALOG_DEMAND               205
#define IDC_BTN_NAVI                    1001
#define IDC_STA_TIME                    1002
#define IDC_STA_SYSSET_TITILE           1003
#define IDC_BTN_EXIT                    1004
#define IDC_BTN_TIME_SET                1005
#define IDC_BTN_DEFAULT_SET             1006
#define IDC_BTN_LANGUAGE_F              1006
#define IDC_BTN_LIGHTENESS_SET          1007
#define IDC_BTN_LANGUAGE_B              1007
#define IDC_BTN_ADJUST                  1007
#define IDC_BTN_MOVIE                   1008
#define IDC_BTN_SPARE_SET               1008
#define IDC_STA_LANGUAGE_COUNTRY_ICO    1008
#define IDC_BTN_RADIO                   1009
#define IDC_BTN_LANGUAGE_SET            1009
#define IDC_BTN_MUSIC                   1010
#define IDC_BTN_SKIN_SET                1010
#define IDC_BTN_SYSSET                  1011
#define IDC_BTN_LANGUAGE_OK             1011
#define IDC_BTN_PIC                     1012
#define IDC_BTN_LANGUAGE_CANCEL         1012
#define IDC_BTN_LANSET_EN               1012
#define IDC_BTN_ABOUT                   1013
#define IDC_STA_LANGUAGE_COUNTRY        1013
#define IDC_BTN_BLUETOOTH               1013
#define IDC_BTN_SCREEN                  1014
#define IDC_STA_LANGUAGE_TITILE         1014
#define IDC_STA_SKIN_SET_TITILE         1015
#define IDC_BTN_SKIN1                   1016
#define IDC_BTN_SKIN2                   1017
#define IDC_BTN_SKINSET_OK              1018
#define IDC_BTN_SKINSET_CANCEL          1019
#define IDC_BTN_SWITCH                  1019
#define IDC_BTN_SPARESET                1020
#define IDC_BTN_INFO_SCREEN             1020
#define IDC_BTN_POWERSET_RETURN         1021
#define IDC_BTN_INFO_ABOUT              1021
#define IDC_STA_ABOUT_TITILE            1022
#define IDC_BTN_ABOUT_B                 1023
#define IDC_BTN_ABOUT_F                 1024
#define IDC_BTN_ABOUT_EXIT              1025
#define IDC_STA_ABOUT                   1026
#define IDC_STA_BRIGHTSET_TITILE        1027
#define IDC_BTN_BRUGHTSET_B             1028
#define IDC_BTN_BRUGHTSET_1             1028
#define IDC_BTN_BRUGHTSET_F             1029
#define IDC_BTN_BRUGHTSET_3             1029
#define IDC_PROGRESS_BRIGHTSET          1030
#define IDC_BTN_BRUGHTSET_2             1030
#define IDC_BTN_BRIGHTSET_EXIT          1031
#define IDC_STA_ICO                     1032
#define IDC_STATIC_ZONE                 1032
#define IDC_BTN_ZONE_B                  1033
#define IDC_STA_ZONE_BMP                1033
#define IDC_BTN_ZONE_F                  1034
#define IDC_BTN_TIMESET_OK              1035
#define IDC_BTN_TIMESET_BACK            1036
#define IDC_BTN_TIMESET                 1037
#define IDC_BTN_TIMEFORMAT              1038
#define IDC_BTN_ZONESET                 1039
#define IDC_STA_TIMEFORMAT              1040
#define IDC_BTN_HOUR_ADD                1041
#define IDC_BTN_MINUTE_ADD              1042
#define IDC_BTN_HOUR_SUB                1043
#define IDC_BTN_MINUTE_SUB              1044
#define IDC_STA_CUR_HOUR                1045
#define IDC_STA_CUR_MINUTE              1046
#define IDC_STA_CUR_SECOND              1049
#define IDC_BTN_SECOND_ADD              1050
#define IDC_BTN_SECOND_SUB              1051
#define IDC_BTN_TIMEUNIT                1053
#define IDC_BTN_TIMEUNIT_12             1053
#define IDC_BTN_APP                     1053
#define IDC_BTN_WINCE                   1054
#define IDC_BTN_TIMEUNIT_24             1055
#define IDC_STC_BATTERY                 1056
#define IDC_STC_TEST                    1057
#define IDC_STA_TIMEZONE                1058
#define IDC_STATIC_TEST                 1059
#define IDC_BTN_INFO_EXIT               1060
#define IDC_STA_INFO                    1061
#define IDC_BTN_TIP_RETURN              1062
#define IDC_BUTTON1                     1063
#define IDC_BUTTON_GAME                 1063
#define IDC_BUTTON_SEARCH               1063
#define IDC_BTN_SEARCH                  1063
#define IDC_BTN_PANEL_BACKSPACE         1063
#define IDC_BTN_NAME                    1063
#define IDC_BTN_SHUT                    1063
#define IDC_BTN_PAGEUP                  1063
#define IDC_BTN_NAVI_1                  1063
#define IDC_BTN_SYSSET_12               1063
#define IDC_BTN_FMT_12                  1063
#define IDC_BTN_ZONE_EXIT               1063
#define IDC_BTN_EBOOK_EXIT              1063
#define IDC_BTN_GPSSTAR_EXIT            1063
#define IDC_BTN_VER_EXIT                1063
#define IDC_1                           1063
#define IDC_BTN_RESET                   1063
#define IDC_BUTTON_ACCEPT               1063
#define IDC_BTN_LOW                     1063
#define IDC_BUTTON_INFO_EXIT            1063
#define IDC_BTN_LANSET_CN               1064
#define IDC_STATIC_SETTING              1064
#define IDC_BUTTON_GAME2                1064
#define IDC_BTN_NUM                     1064
#define IDC_BTN_PAGEDOWN                1064
#define IDC_BUTTON_REJECT               1064
#define IDC_STATIC_ADJUST               1065
#define IDC_BUTTON_GAME4                1065
#define IDC_BUTTON_SYS_DOWN             1066
#define IDC_BUTTON_GAME3                1066
#define IDC_BUTTON_SYS_UP               1067
#define IDC_BUTTON_GAME6                1067
#define IDC_BUTTON_GAME1                1068
#define IDC_BUTTON_EXIT                 1069
#define IDC_BUTTON_GAME5                1070
#define IDC_BUTTON_BLUETOOTH            1071
#define IDC_BUTTON_GAME7                1071
#define IDC_BUTTON_PHONEBOOK            1072
#define IDC_BUTTON_GAME8                1072
#define IDC_BUTTON__BLUETOOTH_QUIT      1073
#define IDC_BTN_BACK                    1074
#define IDC_BTN_PHONEBOOK1              1075
#define IDC_BTN_PHONEBOOK2              1076
#define IDC_BTN_PHONEBOOK3              1077
#define IDC_BTN_PHONEBOOK4              1078
#define IDC_BTN_PHONEBOOK5              1079
#define IDC_BTN_LOG                     1080
#define IDC_BTN_DIA                     1081
#define IDC_BTN_0                       1081
#define IDC_BTN_UP                      1082
#define IDC_BTN_1                       1082
#define IDC_BTN_DOWN                    1083
#define IDC_BTN_2                       1083
#define IDC_BTN_EDIT                    1084
#define IDC_BTN_3                       1084
#define IDC_BTN_4                       1085
#define IDC_BTN_5                       1086
#define IDC_BTN_6                       1087
#define IDC_BTN_7                       1088
#define IDC_BTN_8                       1089
#define IDC_BTN_9                       1090
#define IDC_BTN_10                      1091
#define IDC_BTN_11                      1092
#define IDC_BTN_DiaOut                  1093
#define IDC_BTN_DiaIn                   1094
#define IDC_STATIC_NUM                  1095
#define IDC_EDIT_PANEL_RESULT           1096
#define IDC_BTN_PANEL_INPUTTYPE         1098
#define IDC_STC_PANEL_MAIN              1100
#define IDC_BTN_DIALOUT                 1101
#define IDC_STATIC_NAME                 1102
#define IDC_STATIC_PHONENUM             1103
#define IDC_BTN_OK                      1105
#define IDC_BTN_CANCEL                  1106
#define IDC_BTN_DEL                     1108
#define IDC_BTN_ITEM1                   1108
#define IDC_BTN_ITEM2                   1109
#define IDC_BTN_ITEM3                   1110
#define IDC_BTN_ITEM4                   1111
#define IDC_BTN_ITEM5                   1112
#define IDC_BTN_DEL_ALL                 1113
#define IDC_BTN_NAVI_2                  1114
#define IDC_BTN_DEVICE1                 1116
#define IDC_BTN_DEVICE2                 1117
#define IDC_BTN_DEVICE4                 1118
#define IDC_BTN_DEVICE3                 1119
#define IDC_BTN_DEVICE5                 1120
#define IDC_BTN_MAIN_GAME               1121
#define IDC_BTN_MAIN_EBOOK              1122
#define IDC_BTN_SYSSET_TIMEZONE         1123
#define IDC_BTN_SYSSET_CLOCK            1124
#define IDC_BUTTON2                     1125
#define IDC_BTN_FMT_24                  1125
#define IDC_BTN_TIMEZONE_B              1125
#define IDC_BTN_NAVI_3                  1125
#define IDC_BTN_EBOOK_PDF               1125
#define IDC_BTN_DIAL_INOUT              1125
#define IDC_2                           1125
#define IDC_BTN_MID                     1125
#define IDC_BTN_INFO_GPSINFO            1125
#define IDC_BTN_VOLUP                   1125
#define IDC_BTN_SYSSET_FOR              1125
#define IDC_BTN_FMT_EXIT                1126
#define IDC_BTN_TIMEZONE_F              1127
#define IDC_STATIC_ZONE_TEXT            1128
#define IDC_BTN_NAVI_4                  1129
#define IDC_BTN_EBOOK_WORD              1130
#define IDC_BTN_EBOOK_PPT               1131
#define IDC_BTN_EBOOK_WORDPAD           1132
#define IDC_STC_VOLUME                  1133
#define IDC_BTN_DIAL_UI                 1134
#define IDC_STATIC_SKYVIEW              1135
#define IDC_STATIC_SATELLITESIG         1136
#define IDC_3                           1137
#define IDC_ADD                         1138
#define IDC_BTN_ADD                     1138
#define IDC_SUB                         1139
#define IDC_BTN_SUB                     1139
#define IDC_EXIT                        1140
#define IDC_7                           1141
#define IDC_4                           1142
#define IDC_0                           1143
#define IDC_5                           1144
#define IDC_8                           1145
#define IDC_PlusOrNegative              1146
#define IDC_BTN_PLUSorNEGA              1146
#define IDC_PLUSorNEGA                  1146
#define IDC_9                           1147
#define IDC_6                           1148
#define IDC_DOT                         1149
#define IDC_BTN_DOT                     1149
#define IDC_DIV                         1150
#define IDC_BTN_DIV                     1150
#define IDC_MUL                         1151
#define IDC_BTN_MUL                     1151
#define IDC_BACKSPACE                   1152
#define IDC_BTN_BACKSPACE               1152
#define IDC_CE                          1153
#define IDC_BTN_CE                      1153
#define IDC_EQU                         1154
#define IDC_BTN_EQU                     1154
#define IDC_STATIC_Output               1156
#define IDC_STAT_OUTPUT                 1156
#define IDC_STATIC_POWERSTATUS          1157
#define IDC_STATIC_FREQ                 1158
#define IDC_STATIC_LIGHT                1159
#define IDC_BTN_HIGH                    1160
#define IDC_BTN_CALIBRA                 1162
#define IDC_PROGRESS1                   1163
#define IDC_STC_BLUETOOTH               1164
#define IDC_BUTTON3                     1165
#define IDC_BTN_VOLDOWN                 1165
#define IDC_BTN_SYSSET_BACK             1165
#define IDC_BTN_VOL_UP                  1166
#define IDC_BTN_VOL_DOWN                1167
#define IDC_BTN_SYSSET_BT               1168
#define IDC_BTN_SYSSET_BK_LIGHT         1169
#define IDC_BTN_SYASET_CALIBR           1170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
